### ISSUE TITLE
Code ends up generated into wrong directory

### ISSUE THREAD

**Issue by ghostbuster91** [fiadliel/fs2-grpc#223] opened 2020-09-15 12:59 UTC
![Screenshot from 2020-09-15 14-56-55](https://user-images.githubusercontent.com/5662622/93213128-c197de80-f763-11ea-89fc-579070cb0dee.png)

As you can see on the screenshot GreeterFs2Grpc is located under `/fs2-grpc/examples/addressbook` while it has a different package:
```
package examples.addressbook

import _root_.cats.implicits._

trait GreeterFs2Grpc[F[_], A] {
  def greet(request: examples.addressbook.Request, ctx: A): F[examples.addressbook.Response]
  def points(request: examples.addressbook.Request, ctx: A): _root_.fs2.Stream[F, examples.addressbook.Point]
  def bidi(request: _root_.fs2.Stream[F, examples.addressbook.Point], ctx: A): _root_.fs2.Stream[F, examples.addressbook.Response]
}
```

This prevents project from compiling.
scalaVersion = "2.12.10"
sbt = 1.3.8

**Comment by ahjohannessen** [comment] 2020-09-15 13:42
The same happens with `scalapb/examples/addressbook` - where do you expect `fs2-grpc/examples/addressbook` to end up?

**Comment by ghostbuster91** [comment] 2020-09-15 14:49
Hmm, indeed, you are right, but somehow I am able to use code from `scalapb/examples/addressbook` and unable to use it from `fs2-grpc/examples/addressbook`. 

In the begging I though that it should simply end up in `examples/addressbook`.

**Comment by ghostbuster91** [comment] 2020-09-15 14:57
I guess that the problem is the `-` in the name of the directory

**Comment by ahjohannessen** [comment] 2020-09-15 15:01
Perhaps you could show some output from `sbt` - not sure what the issue is.

**Comment by ghostbuster91** [comment] 2020-09-15 15:02
I just found out that the project compiles using sbt, but the code is not recognized by IntellijIdea: 
![Screenshot from 2020-09-15 17-01-26](https://user-images.githubusercontent.com/5662622/93227897-2dcf0e00-f775-11ea-98b1-dba44b6f997a.png)

**Comment by ahjohannessen** [comment] 2020-09-15 15:10
What is that `ServerBuilder`? an alias for `NettyServerBuilder` ? Also, it might help IDEA to reload sbt projects (upper right sbt button) - or delete .idea folder from project and do a fresh import from existing sources in IDEA.

**Comment by ghostbuster91** [comment] 2020-09-15 15:13
`ServerBuilder` is from `io.grpc` 

I did reload sbt project couple of times already.

**Comment by ghostbuster91** [comment] 2020-09-15 15:19
Still the problem remains. If you take a closer look at my first screenshot, the directory with fs2-grpc has a different icon than scalapb directory

**Comment by ghostbuster91** [comment] 2020-09-16 10:14
Ok, so I checked it also against another project - bootzooka which uses scala 2.13 and the problem remains. You can check it out here: https://github.com/softwaremill/bootzooka/tree/fs2grpc-intellij-idea

This project also uses buildInfo plugin and I notice that it has similar problem as it also has `-` inside its directory name.

![Screenshot from 2020-09-16 12-14-11](https://user-images.githubusercontent.com/5662622/93324428-27dd3980-f816-11ea-8704-20245a405fa1.png)

**Comment by ahjohannessen** [comment] 2020-09-16 10:43
I have made the path customizable here #224 - If it gets merged then you can customize the path by setting this in your project:

```
fs2GrpcOutputPath := (sourceManaged in Compile).value / "fs2_grpc"
```

**Comment by ghostbuster91** [comment] 2020-09-16 11:32
Awesome, thanks!

**Closed** 2021-04-04 16:29 UTC
